paths-ignore:
  - "apps/vault/website/content/**.mdx"
  - "packages/vault/website/content/**.mdx"
  - "apps/vault/builtin/credential/aws/**_test.go"
  - "packages/vault/builtin/credential/aws/**_test.go"
  - "apps/vault/ui/tests/unit/lib/**-test.js"
  - "packages/vault/ui/tests/unit/lib/**-test.js"
